---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: rpm-signing-pipeline
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton pipeline for rpm signing. It is meant to be used by the rh-sign-rpm task, not as a standalone managed
    pipeline.
  params:
    - name: pipeline_image
      description: An image with rh-siging-client needed for the signing
      type: string
    - name: keytab_file
      description: keytab file which is used when running with rh-siging-client tool
      type: string
    - name: secret_name
      description: Service account name
      type: string
    - name: sign_key_alias
      description: Sign key alias
      type: string
    - name: component_name
      description: Name of the component to be signed
      type: string
    - name: component_artifact
      description: OCI artifact URL containing all component files
      type: string
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored
      type: string
    - name: taskGitUrl
      description: The url to the git repo where the release-service-catalog tasks to be used are stored
      default: https://github.com/konflux-ci/release-service-catalog.git
      type: string
    - name: taskGitRevision
      description: The revision in the taskGitUrl repo to be used
      type: string
    - name: requester
      description: Name of the user that requested the signing, for auditing purposes
      type: string
  workspaces:
    - name: pipeline
  tasks:
    - name: send-rpm-siging-request
      retries: 5
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/internal/send-rpm-siging-request/send-rpm-siging-request.yaml
      params:
        - name: pipeline_image
          value: $(params.pipeline_image)
        - name: keytab_file
          value: $(params.keytab_file)
        - name: secret_name
          value: $(params.secret_name)
        - name: sign_key_alias
          value: $(params.sign_key_alias)
        - name: component_name
          value: $(params.component_name)
        - name: component_artifact
          value: $(params.component_artifact)
        - name: ociStorage
          value: $(params.ociStorage)
        - name: requester
          value: $(params.requester)
      workspaces:
        - name: data
          workspace: pipeline
          subPath: signing
